name: Pull Request

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Push Docker Image to Github Registry
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: "${{ secrets.PUBLISH_CONTAINER_ACTOR }}"
          password: "${{ secrets.PUBLISH_CONTAINER }}"
          image_name: ${{ github.repository }}/flytecopilot
          image_tag: ${{ github.sha }}
          push_git_tag: true
          registry: docker.pkg.github.com
